### PR TITLE
Fix error when setting new range and value

### PR DESCRIPTION
**Pull request by alexmasnou**
I have noticed that there is an error when updating the range and the value (combined). The error can be reproduced here: https://codesandbox.io/s/0moo1437m0

For solving this error, the range must be updated before changing the 'start' value.

### CODE REVIEW

**Comment by mmarkelov** [comment]
@alexmasnou good catch! Thank you!

**Comment by alexmasnou** [comment]
@mmarkelov sorry for bothering you again. I think the last hotfix have an issue with generated assets. The last fix is not working (see https://codesandbox.io/s/7mmmx92830) but the changes are present in source code.

**Comment by mmarkelov** [comment]
@alexmasnou thank you! Find out that there are problems with publishing package.
Version **2.3.3** should be fix it, and I'll find solution to fix these problems.

**Comment by shivamragnar** [comment]
I guess this is not yet fixed, having dynamic values for `start` prop does not seem to be working. My use case has dynamically switching between a range slider with two handles, and normal slider with one handle. Not sure if this is still a bug in here. @mmarkelov

**Pull request merged**
